// -*- C++ -*-
//
// generated by wxGlade 0.9.3 on Tue May 14 17:11:21 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "wxglade_out.h"

// begin wxGlade: ::extracode
// end wxGlade



RootFrame::RootFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE|wxMAXIMIZE)
{
    // begin wxGlade: RootFrame::RootFrame
    SetSize(wxSize(720, 480));
    property_grid_1 = new wxPropertyGridManager(this, wxID_ANY);
    frame_menubar = new wxMenuBar();
    wxMenu *wxglade_tmp_menu;
    wxglade_tmp_menu = new wxMenu();
    frame_menubar->Append(wxglade_tmp_menu, wxT("File"));
    wxglade_tmp_menu = new wxMenu();
    frame_menubar->Append(wxglade_tmp_menu, wxT("Edit"));
    wxglade_tmp_menu = new wxMenu();
    frame_menubar->Append(wxglade_tmp_menu, wxT("About"));
    SetMenuBar(frame_menubar);

    set_properties();
    do_layout();
    // end wxGlade
}


void RootFrame::set_properties()
{
    // begin wxGlade: RootFrame::set_properties
    SetTitle(wxT("frame"));
    SetBackgroundColour(wxColour(56, 56, 230));
    // end wxGlade
}


void RootFrame::do_layout()
{
    // begin wxGlade: RootFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(property_grid_1, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}


class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    RootFrame* frame = new RootFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frame);
    frame->Show();
    return true;
}
