// -*- C++ -*-
//
// generated by wxGlade 0.9.3 on Tue May 14 17:11:21 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef WXGLADE_OUT_H
#define WXGLADE_OUT_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/propgrid/manager.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class RootFrame: public wxFrame {
public:
    // begin wxGlade: RootFrame::ids
    // end wxGlade

    RootFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: RootFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: RootFrame::attributes
    wxPropertyGridManager* property_grid_1;
    wxMenuBar* frame_menubar;
    // end wxGlade
}; // wxGlade: end class


#endif // WXGLADE_OUT_H
