#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.9.3 on Tue May 21 17:43:28 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
global grid_sizer_1

class MyFrame(wx.Frame):
    
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.button_2 = wx.Button(self, wx.ID_ANY, "button_2")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.add_new_button, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        global grid_sizer_1
        grid_sizer_1 = wx.GridBagSizer(0, 0)
        grid_sizer_1.Add(self.button_2, (0, 2), (1, 1), 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def add_new_button(self, event):  # wxGlade: MyFrame.<event_handler>
        # print("Event handler 'add_new_button' not implemented!")
        # event.Skip()
        self.button_3 = wx.Button(self, wx.ID_ANY, "button_3")
        grid_sizer_1.Add(self.button_3, (2, 2), (1, 1), 0, 0)


# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
